version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}  # Usando a variável de ambiente do sistema
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    env_file:  # Carregando variáveis de ambiente do arquivo .env
      - .env
